<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Multiplies the maximum stack size of all items and buildings.</Description>
    <Version>1.1.0</Version>
    <BepInExPluginGuid>com.Valoneu.StacksizeMultiplier</BepInExPluginGuid>
    <BepInExPluginName>StacksizeMultiplier</BepInExPluginName>
    <BepInExPluginVersion>1.1.0</BepInExPluginVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\Shared\Shared.cs" Link="Shared.cs" />
  </ItemGroup>
</Project>
