<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Allows placing logistics stations closer together.</Description>
    <Version>1.1.0</Version>
    <BepInExPluginGuid>com.Valoneu.CloserStations</BepInExPluginGuid>
    <BepInExPluginName>CloserStations</BepInExPluginName>
    <BepInExPluginVersion>1.1.0</BepInExPluginVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\Shared\Shared.cs" Link="Shared.cs" />
  </ItemGroup>
</Project>