<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>LessVesselPower</Description>
    <Version>1.0.0</Version>
    <AssemblyName>com.Valoneu.LessVesselPower</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>
</Project>