<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>FactoryOverclock</Description>
    <Version>3.0.0</Version>
    <BepInExPluginGuid>com.Valoneu.FactoryOverclock</BepInExPluginGuid>
    <BepInExPluginName>FactoryOverclock</BepInExPluginName>
    <BepInExPluginVersion>3.0.0</BepInExPluginVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\Shared\Shared.cs" Link="Shared.cs" />
    <PackageReference Include="DysonSphereProgram.Modding.DSPModSave" Version="1.2.0" />
    <PackageReference Include="DysonSphereProgram.Modding.LDBTool" Version="3.0.0" />
    <PackageReference Include="DysonSphereProgram.Modding.NebulaMultiplayerModApi" Version="2.0.0" />
  </ItemGroup>
</Project>