<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>PlanetMinerFast</Description>
    <Version>1.0.2</Version>
    <BepInExPluginGuid>com.Valoneu.PlanetMinerFast</BepInExPluginGuid>
    <BepInExPluginName>PlanetMinerFast</BepInExPluginName>
    <BepInExPluginVersion>1.0.2</BepInExPluginVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Shared\Shared.cs" Link="Shared.cs" />
  </ItemGroup>
</Project>
