<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>CustomWarpSound</Description>
    <Version>1.0.10</Version>
    <BepInExPluginGuid>com.Valoneu.CustomWarpSound</BepInExPluginGuid>
    <BepInExPluginName>CustomWarpSound</BepInExPluginName>
    <BepInExPluginVersion>1.0.10</BepInExPluginVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>
</Project>