<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Visualizes logistics vessel routes in the Star Map.</Description>
    <Version>1.2.1</Version>
    <BepInExPluginGuid>com.Valoneu.VesselTrails</BepInExPluginGuid>
    <BepInExPluginName>VesselTrails</BepInExPluginName>
    <BepInExPluginVersion>1.2.1</BepInExPluginVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>
</Project>
