<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>PilerMax</Description>
    <Version>1.0.0</Version>
    <BepInExPluginGuid>com.Valoneu.PilerMax</BepInExPluginGuid>
    <BepInExPluginName>PilerMax</BepInExPluginName>
    <BepInExPluginVersion>1.0.0</BepInExPluginVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>
</Project>