<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>SpaciousStations</AssemblyName>
    <Description>Multiplies station drone/ship counts, storage capacity and charge power.</Description>
    <Version>1.2.2</Version>
    <BepInExPluginGuid>com.Valoneu.SpaciousStations</BepInExPluginGuid>
    <BepInExPluginName>SpaciousStations</BepInExPluginName>
    <BepInExPluginVersion>1.2.2</BepInExPluginVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\Shared\Shared.cs" Link="Shared.cs" />
  </ItemGroup>
</Project>
