<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Multiplies station drone/ship counts, storage capacity and charge power.</Description>
    <Version>1.0.3</Version>
    <BepInExPluginGuid>com.Valoneu.SpaciousStations</BepInExPluginGuid>
    <BepInExPluginName>SpaciousStations</BepInExPluginName>
    <BepInExPluginVersion>1.0.3</BepInExPluginVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>
</Project>
