using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using HarmonyLib;
using BepInEx;
using DysonSphereMods.Shared;
using UnityEngine;
using CommonAPI;
using CommonAPI.Systems;
using CommonAPI.Systems.ModLocalization;
using System.Reflection.Emit;

namespace InfinityTechnologies
{
    [BepInPlugin(MOD_GUID, MOD_NAME, MOD_VERSION)]
    [BepInProcess("DSPGAME.exe")]
    [BepInDependency(CommonAPIPlugin.GUID)]
    [CommonAPISubmoduleDependency(nameof(ProtoRegistry), nameof(LocalizationModule))]
    public class InfinityTechnologiesPlugin : BaseUnityPlugin
    {
        public const string MOD_GUID = "com.Valoneu.InfinityTechnologies";
        public const string MOD_NAME = "InfinityTechnologies";
        public const string MOD_VERSION = "1.0.0";

        // Multipliers calculated from tech levels — always >= 1.0
        public static float SpherePowerMultiplier = 1f;
        public static float ProliferatorMultiplier = 1f;
        public static float FuelEfficiencyMultiplier = 1f;
        public static float CombatSpeedMultiplier = 1f;
        public static float RayReceiverMultiplier = 1f;
        public static float AccumulatorMultiplier = 1f;
        public static float WirelessPowerMultiplier = 1f;
        public static float ResearchProductivityMultiplier = 1f;
        public static int AutoRepairBonus = 0;

        private void Awake()
        {
            Log.Init(Logger);
            var harmony = new Harmony(MOD_GUID);
            harmony.PatchAll(typeof(InfinityTechnologiesPlugin));

            RegisterStrings();
            RegisterInfiniteTechs();

            Log.Info($"{MOD_NAME} v{MOD_VERSION} loaded!");
        }

        private void RegisterStrings()
        {
            LocalizationModule.RegisterTranslation("TechName_9001", "Infinite Inventory");
            LocalizationModule.RegisterTranslation("TechDesc_9001", "Increases the player's inventory capacity further (adds 1 row and 1 column per level).");
            LocalizationModule.RegisterTranslation("TechName_9002", "Wireless Power Boost");
            LocalizationModule.RegisterTranslation("TechDesc_9002", "Increases the speed at which the mecha charges from wireless power towers.");
            LocalizationModule.RegisterTranslation("TechName_9003", "Ray Receiver Overclock");
            LocalizationModule.RegisterTranslation("TechDesc_9003", "Increases the maximum power output of Ray Receivers.");
            LocalizationModule.RegisterTranslation("TechName_9004", "Accumulator Optimization");
            LocalizationModule.RegisterTranslation("TechDesc_9004", "Increases the charge and discharge speed of Accumulators.");
            LocalizationModule.RegisterTranslation("TechName_9005", "Auto-Repair Efficiency");
            LocalizationModule.RegisterTranslation("TechDesc_9005", "Increases the speed at which construction drones repair structures.");
            LocalizationModule.RegisterTranslation("TechName_9006", "Infinite Logistics Slots");
            LocalizationModule.RegisterTranslation("TechDesc_9006", "Increases the number of player's personal logistics slots.");

            LocalizationModule.RegisterTranslation("TechName_9051", "Dyson Sphere Efficiency");
            LocalizationModule.RegisterTranslation("TechDesc_9051", "Increases the total power output generated by the Dyson Sphere.");
            LocalizationModule.RegisterTranslation("TechName_9052", "Proliferator Enhancement");
            LocalizationModule.RegisterTranslation("TechDesc_9052", "Increases the extra output/speed bonus from Proliferated items.");
            LocalizationModule.RegisterTranslation("TechName_9053", "Advanced Fuel Consumption");
            LocalizationModule.RegisterTranslation("TechDesc_9053", "Increases the energy yield of all fuels burned in the mecha.");
            LocalizationModule.RegisterTranslation("TechName_9054", "Logistics Combat Optimization");
            LocalizationModule.RegisterTranslation("TechDesc_9054", "Increases shooting speed of turrets, drones and vessels.");
            LocalizationModule.RegisterTranslation("TechName_9055", "Research Productivity");
            LocalizationModule.RegisterTranslation("TechDesc_9055", "Increases the amount of research hashes produced per matrix consumed.");

            LocalizationModule.RegisterTranslation("TechFunction_102", "Wireless charging power +{0:P0}");
            LocalizationModule.RegisterTranslation("TechFunction_103", "Ray receiver output +{0:P0}");
            LocalizationModule.RegisterTranslation("TechFunction_104", "Accumulator throughput +{0:P0}");
            LocalizationModule.RegisterTranslation("TechFunction_105", "Drone repair speed +{0:P0}");
            LocalizationModule.RegisterTranslation("TechFunction_106", "Sphere energy extraction +{0:P0}");
            LocalizationModule.RegisterTranslation("TechFunction_107", "Proliferation effects +{0:P1}");
            LocalizationModule.RegisterTranslation("TechFunction_108", "Fuel efficiency +{0:P0}");
            LocalizationModule.RegisterTranslation("TechFunction_109", "Combat fire rate +{0:P0}");
            LocalizationModule.RegisterTranslation("TechFunction_110", "Research hashes +{0:P0}");
        }

        private void RegisterInfiniteTechs()
        {
            // Normal Price Techs (9000-9049)
            
            // 9001: Bigger Inventory (+1 row and +1 column per level)
            var inventoryTech = ProtoRegistry.RegisterTech(9001, "TechName_9001", "TechDesc_9001", 
                "Inventory capacity expanded.", 
                "Icons/Tech/2104", 
                new int[0], 
                new int[] { 6006 }, 
                new int[] { 1000 }, 
                50000000, 
                new int[0], 
                new Vector2(42, 10)
            );
            inventoryTech.MaxLevel = 3; 
            inventoryTech.LevelCoef1 = 50000000;
            inventoryTech.UnlockFunctions = new int[] { 5, 38 }; // 5 = row, 38 = column
            inventoryTech.UnlockValues = new double[] { 1.0, 1.0 };

            // 9002: Wireless Charging Rate (+20% per level)
            var wirelessTech = ProtoRegistry.RegisterTech(9002, "TechName_9002", "TechDesc_9002", 
                "Wireless charging efficiency improved.", 
                "Icons/Tech/1503", 
                new int[0], 
                new int[] { 6006 }, 
                new int[] { 1000 }, 
                50000000, 
                new int[0], 
                new Vector2(42, 6)
            );
            wirelessTech.MaxLevel = 100000;
            wirelessTech.LevelCoef1 = 50000000;
            wirelessTech.UnlockFunctions = new int[] { 102 };
            wirelessTech.UnlockValues = new double[] { 0.2 };

            // 9003: Ray Receiver Max Power (+10% per level)
            var rayReceiverTech = ProtoRegistry.RegisterTech(9003, "TechName_9003", "TechDesc_9003", 
                "Ray receiver capacity upgraded.", 
                "Icons/Tech/1508", 
                new int[0], 
                new int[] { 6006 }, 
                new int[] { 1000 }, 
                100000000, 
                new int[0], 
                new Vector2(42, 2)
            );
            rayReceiverTech.MaxLevel = 100000;
            rayReceiverTech.LevelCoef1 = 100000000;
            rayReceiverTech.UnlockFunctions = new int[] { 103 };
            rayReceiverTech.UnlockValues = new double[] { 0.1 };

            // 9004: Accumulator Performance (+20% per level)
            var accumulatorTech = ProtoRegistry.RegisterTech(9004, "TechName_9004", "TechDesc_9004", 
                "Accumulator throughput increased.", 
                "Icons/Tech/1501", 
                new int[0], 
                new int[] { 6006 }, 
                new int[] { 1000 }, 
                25000000, 
                new int[0], 
                new Vector2(42, -2)
            );
            accumulatorTech.MaxLevel = 100000;
            accumulatorTech.LevelCoef1 = 25000000;
            accumulatorTech.UnlockFunctions = new int[] { 104 };
            accumulatorTech.UnlockValues = new double[] { 0.2 };

            // 9005: Drone Repair Speed (+10% per level)
            var repairTech = ProtoRegistry.RegisterTech(9005, "TechName_9005", "TechDesc_9005", 
                "Repair speed enhanced.", 
                "Icons/Tech/2407", 
                new int[0], 
                new int[] { 6006 }, 
                new int[] { 1000 }, 
                80000000, 
                new int[0], 
                new Vector2(42, -6)
            );
            repairTech.MaxLevel = 100000;
            repairTech.LevelCoef1 = 80000000;
            repairTech.UnlockFunctions = new int[] { 105 };
            repairTech.UnlockValues = new double[] { 0.1 };

            // 9006: Personal Logistics Slots (+1 slot per level)
            var logisticTech = ProtoRegistry.RegisterTech(9006, "TechName_9006", "TechDesc_9006", 
                "Personal logistics expanded.", 
                "Icons/Tech/3201", 
                new int[0], 
                new int[] { 6006 }, 
                new int[] { 1000 }, 
                10000000, 
                new int[0], 
                new Vector2(42, -10)
            );
            logisticTech.MaxLevel = 100000;
            logisticTech.LevelCoef1 = 10000000;
            logisticTech.UnlockFunctions = new int[] { 32 }; // 32 = personal logistics column
            logisticTech.UnlockValues = new double[] { 1.0 };

            // Giga Price Techs (9050-9099) - These require White Science (6006)
            
            // 9051: Sphere Power Output (+1% per level)
            var sphereTech = ProtoRegistry.RegisterTech(9051, "TechName_9051", "TechDesc_9051", 
                "Sphere energy extraction improved.", 
                "Icons/Tech/1510", 
                new int[0], 
                new int[] { 6006 }, 
                new int[] { 1000 }, 
                10000000000L, 
                new int[0], 
                new Vector2(50, 10)
            );
            sphereTech.MaxLevel = 100000;
            unchecked { sphereTech.LevelCoef1 = (int)10000000000L; }
            sphereTech.UnlockFunctions = new int[] { 106 };
            sphereTech.UnlockValues = new double[] { 0.01 };

            // 9052: More Proliferation Multiplier (+0.25% per level)
            var proliferatorTech = ProtoRegistry.RegisterTech(9052, "TechName_9052", "TechDesc_9052", 
                "Proliferation effects strengthened.", 
                "Icons/Tech/1134", 
                new int[0], 
                new int[] { 6006 }, 
                new int[] { 1000 }, 
                1000000000L, 
                new int[0], 
                new Vector2(50, 5)
            );
            proliferatorTech.MaxLevel = 100;
            unchecked { proliferatorTech.LevelCoef1 = (int)1000000000L; }
            proliferatorTech.UnlockFunctions = new int[] { 107 };
            proliferatorTech.UnlockValues = new double[] { 0.0025 };

            // 9053: Fuel Efficiency (+2% per level)
            var fuelTech = ProtoRegistry.RegisterTech(9053, "TechName_9053", "TechDesc_9053", 
                "Fuel efficiency increased.", 
                "Icons/Tech/1506", 
                new int[0], 
                new int[] { 6006 }, 
                new int[] { 1000 }, 
                200000000L, 
                new int[0], 
                new Vector2(50, 0)
            );
            fuelTech.MaxLevel = 100000;
            unchecked { fuelTech.LevelCoef1 = (int)200000000L; }
            fuelTech.UnlockFunctions = new int[] { 108 };
            fuelTech.UnlockValues = new double[] { 0.02 };

            // 9054: Combat Speed (+5% per level)
            var combatTech = ProtoRegistry.RegisterTech(9054, "TechName_9054", "TechDesc_9054", 
                "Combat fire rate improved.", 
                "Icons/Tech/3107", 
                new int[0], 
                new int[] { 6006 }, 
                new int[] { 1000 }, 
                300000000L, 
                new int[0], 
                new Vector2(50, -5)
            );
            combatTech.MaxLevel = 100000;
            unchecked { combatTech.LevelCoef1 = (int)300000000L; }
            combatTech.UnlockFunctions = new int[] { 109 };
            combatTech.UnlockValues = new double[] { 0.05 };

            // 9055: Research Productivity (+10% per level)
            var researchProdTech = ProtoRegistry.RegisterTech(9055, "TechName_9055", "TechDesc_9055", 
                "Research efficiency greatly improved.", 
                "Icons/Tech/2501", 
                new int[0], 
                new int[] { 6006 }, 
                new int[] { 1000 }, 
                5000000000L, 
                new int[0], 
                new Vector2(50, -10)
            );
            researchProdTech.MaxLevel = 100000;
            unchecked { researchProdTech.LevelCoef1 = (int)5000000000L; }
            researchProdTech.UnlockFunctions = new int[] { 110 };
            researchProdTech.UnlockValues = new double[] { 0.1 };

            inventoryTech.RefreshTranslation();
            wirelessTech.RefreshTranslation();
            rayReceiverTech.RefreshTranslation();
            accumulatorTech.RefreshTranslation();
            repairTech.RefreshTranslation();
            logisticTech.RefreshTranslation();
            sphereTech.RefreshTranslation();
            proliferatorTech.RefreshTranslation();
            fuelTech.RefreshTranslation();
            combatTech.RefreshTranslation();
            researchProdTech.RefreshTranslation();
        }

        // ============================================================================
        //  PATCH: Tech Tree UI — display custom function text
        // ============================================================================
        [HarmonyPostfix]
        [HarmonyPatch(typeof(TechProto), nameof(TechProto.UnlockFunctionText))]
        public static void TechProto_UnlockFunctionText_Postfix(TechProto __instance, ref string __result, StringBuilder sb)
        {
            if (__instance.ID < 9000) return;

            List<string> lines = new List<string>();
            
            bool hasVanilla = false;
            foreach (int funcId in __instance.UnlockFunctions)
            {
                if (funcId < 100) hasVanilla = true;
            }

            for (int i = 0; i < __instance.UnlockFunctions.Length; i++)
            {
                int funcId = __instance.UnlockFunctions[i];
                if (funcId >= 100)
                {
                    string key = $"TechFunction_{funcId}";
                    string translatedFormat = key.Translate();
                    if (translatedFormat != key)
                    {
                        lines.Add(string.Format(translatedFormat, __instance.UnlockValues[i]));
                    }
                }
            }

            if (lines.Count > 0)
            {
                if (string.IsNullOrEmpty(__result) || !hasVanilla)
                    __result = string.Join("\r\n", lines);
                else
                    __result += "\r\n" + string.Join("\r\n", lines);
            }
        }

        // ============================================================================
        //  PATCH: When a tech function is unlocked — recalculate our multipliers
        // ============================================================================
        [HarmonyPostfix]
        [HarmonyPatch(typeof(GameHistoryData), "UnlockTechFunction")]
        public static void GameHistoryData_UnlockTechFunction_Postfix(int func, double value, int level)
        {
            if (func >= 102 && func <= 110)
            {
                RecalculateModifiers();
            }
        }

        // ============================================================================
        //  PATCH: Recalculate on game load
        // ============================================================================
        [HarmonyPostfix]
        [HarmonyPatch(typeof(GameMain), "Begin")]
        public static void GameMain_Begin_Postfix()
        {
            RecalculateModifiers();
        }

        // ============================================================================
        //  Core modifier calculation from tech levels
        // ============================================================================
        public static void RecalculateModifiers()
        {
            var history = GameMain.history;
            if (history == null || LDB.techs == null) return;

            SpherePowerMultiplier = 1f;
            ProliferatorMultiplier = 1f;
            FuelEfficiencyMultiplier = 1f;
            CombatSpeedMultiplier = 1f;
            RayReceiverMultiplier = 1f;
            AccumulatorMultiplier = 1f;
            WirelessPowerMultiplier = 1f;
            ResearchProductivityMultiplier = 1f;
            AutoRepairBonus = 0;

            // Helper: given a tech ID and per-level bonus, compute 1 + levels * bonus
            float CalcMultiplier(int techId, float perLevel)
            {
                if (history.techStates.TryGetValue(techId, out var state))
                {
                    var proto = LDB.techs.Select(techId);
                    if (proto != null)
                    {
                        int levels = Math.Max(0, state.curLevel - proto.Level);
                        return 1f + levels * perLevel;
                    }
                }
                return 1f;
            }

            int CalcLevels(int techId)
            {
                if (history.techStates.TryGetValue(techId, out var state))
                {
                    var proto = LDB.techs.Select(techId);
                    if (proto != null)
                        return Math.Max(0, state.curLevel - proto.Level);
                }
                return 0;
            }

            WirelessPowerMultiplier = CalcMultiplier(9002, 0.2f);
            RayReceiverMultiplier = CalcMultiplier(9003, 0.1f);
            AccumulatorMultiplier = CalcMultiplier(9004, 0.2f);
            SpherePowerMultiplier = CalcMultiplier(9051, 0.01f);
            ProliferatorMultiplier = CalcMultiplier(9052, 0.0025f);
            FuelEfficiencyMultiplier = CalcMultiplier(9053, 0.02f);
            CombatSpeedMultiplier = CalcMultiplier(9054, 0.05f);
            ResearchProductivityMultiplier = CalcMultiplier(9055, 0.1f);
            AutoRepairBonus = CalcLevels(9005);

            // Update Dyson Sphere power output
            if (GameMain.data != null && GameMain.data.dysonSpheres != null)
            {
                foreach (var ds in GameMain.data.dysonSpheres)
                {
                    if (ds == null) continue;
                    UpdateDysonSpherePower(ds);
                }
            }

            // Proliferator table modifications
            if (ProliferatorMultiplier > 1.0001f)
            {
                for (int i = 1; i <= 10; i++)
                {
                    if (i == 1 || i == 2 || i == 4)
                    {
                        double baseInc = i == 1 ? 0.125 : (i == 2 ? 0.2 : 0.25);
                        Cargo.incTableMilli[i] = Math.Min(0.5, baseInc * ProliferatorMultiplier);
                        Cargo.accTableMilli[i] = Math.Min(2.5, (double)Cargo.accTable[i] / 1000.0 * ProliferatorMultiplier);
                    }
                }
            }
        }

        public static void UpdateDysonSpherePower(DysonSphere ds)
        {
            if (ds == null || ds.starData == null || SpherePowerMultiplier <= 1.0001f) return;
            float lumino = ds.starData.dysonLumino;
            ds.energyGenPerSail = (long)(Configs.freeMode.solarSailEnergyPerTick * lumino * SpherePowerMultiplier);
            ds.energyGenPerNode = (long)(Configs.freeMode.dysonNodeEnergyPerTick * lumino * SpherePowerMultiplier);
            ds.energyGenPerFrame = (long)(Configs.freeMode.dysonFrameEnergyPerTick * lumino * SpherePowerMultiplier);
            ds.energyGenPerShell = (long)(Configs.freeMode.dysonShellEnergyPerTick * lumino * SpherePowerMultiplier);
            
            var field = typeof(DysonSphere).GetField("needRecalculatePower", BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);
            if (field != null) field.SetValue(ds, true);
        }

        [HarmonyPostfix]
        [HarmonyPatch(typeof(DysonSphere), nameof(DysonSphere.Init))]
        public static void DysonSphere_Init_Postfix(DysonSphere __instance)
        {
            UpdateDysonSpherePower(__instance);
        }

        // ============================================================================
        //  PATCH: Apply combat upgrades on-the-fly (non-accumulating)
        // ============================================================================
        [HarmonyPostfix]
        [HarmonyPatch(typeof(GameHistoryData), nameof(GameHistoryData.GetCombatUpgradeData))]
        public static void GameHistoryData_GetCombatUpgradeData_Postfix(ref CombatUpgradeData combatUpgradeData)
        {
            if (CombatSpeedMultiplier > 1.001f)
            {
                float bonus = (CombatSpeedMultiplier - 1f);
                combatUpgradeData.combatDroneROFRatio += bonus;
                combatUpgradeData.combatShipROFRatio += bonus;
            }
        }

        // ============================================================================
        //  PATCH: Apply auto-repair bonus on-the-fly in GameTick
        // ============================================================================
        [HarmonyPrefix]
        [HarmonyPatch(typeof(ConstructionModuleComponent), nameof(ConstructionModuleComponent.GameTick))]
        public static void ConstructionModuleComponent_GameTick_Prefix(ref ConstructionModuleComponent __instance)
        {
            if (AutoRepairBonus > 0)
            {
                // Each level adds 1.0 repair/s baseline (shared with vanilla speed units)
                __instance.autoReconstructAcc += (float)AutoRepairBonus / 60f;
            }
        }

        // ============================================================================
        //  PATCH: Mecha fuel efficiency — boost energy generated per fuel rod
        // ============================================================================
        [HarmonyPostfix]
        [HarmonyPatch(typeof(Mecha), "reactorPowerGenEnhanced", MethodType.Getter)]
        public static void Mecha_ReactorPowerGen_Postfix(ref double __result)
        {
            if (FuelEfficiencyMultiplier > 1.001f)
                __result *= FuelEfficiencyMultiplier;
        }

        [HarmonyPostfix]
        [HarmonyPatch(typeof(Mecha), "reactorPowerForWeaponEnhanced", MethodType.Getter)]
        public static void Mecha_ReactorPowerForWeapon_Postfix(ref double __result)
        {
            if (FuelEfficiencyMultiplier > 1.001f)
                __result *= FuelEfficiencyMultiplier;
        }

        // ============================================================================
        //  PATCH: Mecha fuel efficiency — make fuel rods last longer
        // ============================================================================
        [HarmonyPrefix]
        [HarmonyPatch(typeof(Mecha), "GenerateEnergy")]
        public static void Mecha_GenerateEnergy_Prefix(Mecha __instance, double dt, out double __state)
        {
            __state = __instance.reactorEnergy;
        }

        [HarmonyPostfix]
        [HarmonyPatch(typeof(Mecha), "GenerateEnergy")]
        public static void Mecha_GenerateEnergy_Postfix(Mecha __instance, double dt, double __state)
        {
            if (FuelEfficiencyMultiplier > 1.001f)
            {
                double consumed = __state - __instance.reactorEnergy;
                if (consumed > 0.0001)
                {
                    // Give back reactor energy so the fuel rod lasts longer
                    __instance.reactorEnergy += consumed * (1.0 - 1.0 / FuelEfficiencyMultiplier);

                    // Add extra core energy from the increased yield
                    double extraCore = consumed * (FuelEfficiencyMultiplier - 1.0);
                    lock (__instance)
                    {
                        __instance.coreEnergy += extraCore;
                        if (__instance.coreEnergy > __instance.coreEnergyCap)
                            __instance.coreEnergy = __instance.coreEnergyCap;
                        __instance.MarkEnergyChange(1, extraCore);
                    }
                }
            }
        }

        // ============================================================================
        //  PATCH: Wireless Power — boost the mecha charge from wireless towers
        // ============================================================================
        [HarmonyPrefix]
        [HarmonyPatch(typeof(Mecha), nameof(Mecha.MarkEnergyChange))]
        public static void Mecha_MarkEnergyChange_Prefix(Mecha __instance, int func, ref double change)
        {
            if (func == 2 && WirelessPowerMultiplier > 1.001f)
            {
                double originalChange = change;
                change *= WirelessPowerMultiplier; // Boost the statistical change
                
                // Boost the REAL energy
                double extra = change - originalChange;
                __instance.coreEnergy += extra;
                if (__instance.coreEnergy > __instance.coreEnergyCap)
                    __instance.coreEnergy = __instance.coreEnergyCap;
            }
        }

        // ============================================================================
        //  PATCH: Ray Receiver — increase energy cap & max output
        // ============================================================================
        [HarmonyPostfix]
        [HarmonyPatch(typeof(PowerGeneratorComponent), nameof(PowerGeneratorComponent.EnergyCap_Gamma_Req))]
        public static void RayReceiver_EnergyCap_Postfix(ref long __result)
        {
            if (RayReceiverMultiplier > 1.001f)
                __result = (long)(__result * RayReceiverMultiplier);
        }

        [HarmonyPostfix]
        [HarmonyPatch(typeof(PowerGeneratorComponent), nameof(PowerGeneratorComponent.MaxOutputCurrent_Gamma))]
        public static void RayReceiver_MaxOutput_Postfix(ref long __result)
        {
            if (RayReceiverMultiplier > 1.001f)
                __result = (long)(__result * RayReceiverMultiplier);
        }

        // ============================================================================
        //  PATCH: Accumulator — increase input/output caps
        // ============================================================================
        [HarmonyPostfix]
        [HarmonyPatch(typeof(PowerAccumulatorComponent), nameof(PowerAccumulatorComponent.InputCap))]
        public static void Accumulator_InputCap_Postfix(ref long __result)
        {
            if (AccumulatorMultiplier > 1.001f)
                __result = (long)(__result * AccumulatorMultiplier);
        }

        [HarmonyPostfix]
        [HarmonyPatch(typeof(PowerAccumulatorComponent), nameof(PowerAccumulatorComponent.OutputCap))]
        public static void Accumulator_OutputCap_Postfix(ref long __result)
        {
            if (AccumulatorMultiplier > 1.001f)
                __result = (long)(__result * AccumulatorMultiplier);
        }

        // ============================================================================
        //  PATCH: Building fuel efficiency — increase max output cap
        // ============================================================================
        [HarmonyPostfix]
        [HarmonyPatch(typeof(PowerGeneratorComponent), "EnergyCap_Fuel")]
        public static void Building_FuelEfficiency_Cap_Postfix(ref long __result)
        {
            if (FuelEfficiencyMultiplier > 1.001f)
                __result = (long)(__result * FuelEfficiencyMultiplier);
        }

        // ============================================================================
        //  PATCH: Turret fire rate — multiply the power parameter
        // ============================================================================
        [HarmonyPrefix]
        [HarmonyPatch(typeof(TurretComponent), "Shoot_Gauss")]
        public static void Turret_Shoot_Gauss_Prefix(ref float power)
        {
            if (CombatSpeedMultiplier > 1.001f)
                power *= CombatSpeedMultiplier;
        }

        [HarmonyPrefix]
        [HarmonyPatch(typeof(TurretComponent), "Shoot_Laser")]
        public static void Turret_Shoot_Laser_Prefix(ref float power)
        {
            if (CombatSpeedMultiplier > 1.001f)
                power *= CombatSpeedMultiplier;
        }

        [HarmonyPrefix]
        [HarmonyPatch(typeof(TurretComponent), "Shoot_Cannon")]
        public static void Turret_Shoot_Cannon_Prefix(ref float power)
        {
            if (CombatSpeedMultiplier > 1.001f)
                power *= CombatSpeedMultiplier;
        }

        [HarmonyPrefix]
        [HarmonyPatch(typeof(TurretComponent), "Shoot_Plasma")]
        public static void Turret_Shoot_Plasma_Prefix(ref float power)
        {
            if (CombatSpeedMultiplier > 1.001f)
                power *= CombatSpeedMultiplier;
        }

        [HarmonyPrefix]
        [HarmonyPatch(typeof(TurretComponent), "Shoot_Missile")]
        public static void Turret_Shoot_Missile_Prefix(ref float power)
        {
            if (CombatSpeedMultiplier > 1.001f)
                power *= CombatSpeedMultiplier;
        }

        [HarmonyPrefix]
        [HarmonyPatch(typeof(TurretComponent), "Shoot_LocalPlasma")]
        public static void Turret_Shoot_LocalPlasma_Prefix(ref float power)
        {
            if (CombatSpeedMultiplier > 1.001f)
                power *= CombatSpeedMultiplier;
        }

        // ============================================================================
        //  PATCH: Research Productivity — multiply hashes produced per research tick
        // ============================================================================
        [HarmonyPrefix]
        [HarmonyPatch(typeof(LabComponent), "InternalUpdateResearch")]
        public static void LabComponent_InternalUpdateResearch_Prefix(
            ref TechState ts, ref long hashRegister, out long __state0, out long __state1)
        {
            __state0 = ts.hashUploaded;
            __state1 = hashRegister;
        }

        [HarmonyPostfix]
        [HarmonyPatch(typeof(LabComponent), "InternalUpdateResearch")]
        public static void LabComponent_InternalUpdateResearch_Postfix(
            ref TechState ts, ref long hashRegister, long __state0, long __state1)
        {
            if (ResearchProductivityMultiplier <= 1.001f) return;

            long prevHash = __state0;
            long prevRegister = __state1;

            long hashDelta = ts.hashUploaded - prevHash;
            long registerDelta = hashRegister - prevRegister;

            if (hashDelta > 0)
            {
                long bonusHash = (long)(hashDelta * (ResearchProductivityMultiplier - 1.0f));
                ts.hashUploaded += bonusHash;
                
                if (ts.hashUploaded > ts.hashNeeded)
                    ts.hashUploaded = ts.hashNeeded;
            }

            if (registerDelta > 0)
            {
                long bonusRegister = (long)(registerDelta * (ResearchProductivityMultiplier - 1.0f));
                hashRegister += bonusRegister;
            }
        }
    }
}
