<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>TechHashReduce</Description>
    <Version>1.2.0</Version>
    <BepInExPluginGuid>com.Valoneu.TechHashReduce</BepInExPluginGuid>
    <BepInExPluginName>TechHashReduce</BepInExPluginName>
    <BepInExPluginVersion>1.2.0</BepInExPluginVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\Shared\Shared.cs" Link="Shared.cs" />
  </ItemGroup>
</Project>