<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>SpaceTargetEverything</AssemblyName>
    <Description>Space vessels target everything on planet not just relay.</Description>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Shared\Shared.cs" Link="Shared.cs" />
  </ItemGroup>

</Project>
