<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Adds a chemical recipe to dissolve excess Hydrogen.</Description>
    <Version>1.1.0</Version>
    <AssemblyName>com.Valoneu.HydrogenDissolution</AssemblyName>
    <BepInExPluginGuid>com.Valoneu.HydrogenDissolution</BepInExPluginGuid>
    <BepInExPluginName>HydrogenDissolution</BepInExPluginName>
    <BepInExPluginVersion>1.1.0</BepInExPluginVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\Shared\Shared.cs" Link="Shared.cs" />
  </ItemGroup>
</Project>
