<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>FactoryOverclock</Description>
    <Version>2.1.7</Version>
    <BepInExPluginGuid>com.Valoneu.FactoryOverclock</BepInExPluginGuid>
    <BepInExPluginName>FactoryOverclock</BepInExPluginName>
    <BepInExPluginVersion>2.1.7</BepInExPluginVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Shared\Shared.csproj" />
    <PackageReference Include="DysonSphereProgram.Modding.DSPModSave" Version="1.2.0" />
    <PackageReference Include="DysonSphereProgram.Modding.LDBTool" Version="3.0.0" />
    <PackageReference Include="DysonSphereProgram.Modding.NebulaMultiplayerModApi" Version="2.0.0" />
  </ItemGroup>
</Project>